//! Systemd user service installation, generation, and removal.

use std::path::{Path, PathBuf};
use std::process::Command;

use crate::config::{config_dir, list_configs};
use crate::daemon::ipc::{current_user, linger_enabled, offer_enable_instance, prompt_yes_no};
use crate::daemon::pid::{systemd_booted, systemd_dir};
use crate::error::BotError;

pub(crate) const SERVICE_NAME: &str = "ttspotify@.service";
pub(crate) const UNIT_FILE_VERSION: u32 = 2;

pub(crate) fn unit_version_from_contents(contents: &str) -> u32 {
    contents
        .lines()
        .find_map(|l| l.strip_prefix("# ttspotify-unit-version: "))
        .and_then(|v| v.trim().parse().ok())
        .unwrap_or(0)
}

pub fn install_service() -> Result<(), BotError> {
    if !systemd_booted() {
        println!("systemd not detected. This installer needs systemd.");
        println!("Run the binary directly, or supervise it with your");
        println!("init system (OpenRC, runit, s6).");
        return Ok(());
    }

    let config_base = write_unit_file()?;

    println!("\nTTSpotify service installed.");
    println!("Config files go in: {}\n", config_base.display());
    println!("Quick start:");
    println!("  tt-spotify-bot --setup myserver");
    println!("  systemctl --user start ttspotify@myserver");
    println!("  systemctl --user enable ttspotify@myserver");
    println!("  journalctl --user -u ttspotify@myserver -f");

    let user = current_user();
    if !user.is_empty() && !linger_enabled(&user) {
        check_and_offer_linger(&user);
    }

    let configs = list_configs();
    for (name, _) in configs {
        offer_enable_instance(&name);
    }

    Ok(())
}

fn check_and_offer_linger(user: &str) {
    println!("\nLingering is off, so the bot would stop when you log out.");
    if prompt_yes_no("Enable linger so it keeps running after logout?") {
        let ok = Command::new("loginctl")
            .args(["enable-linger", user])
            .status()
            .map(|s| s.success())
            .unwrap_or(false);
        if ok {
            println!("Linger enabled.");
        } else {
            println!("Could not enable linger. Run manually: loginctl enable-linger {user}");
        }
    } else {
        println!("Skipped. Enable later with: loginctl enable-linger {user}");
    }
}

pub(crate) fn write_unit_file() -> Result<PathBuf, BotError> {
    let exe_path = std::env::current_exe()
        .map_err(|e| BotError::Config(format!("Cannot determine executable path: {e}")))?;
    let config_base = config_dir();

    let systemd = systemd_dir();
    std::fs::create_dir_all(&systemd)?;
    std::fs::create_dir_all(&config_base)?;

    let service_path = systemd.join(SERVICE_NAME);
    let exec_start = format!(
        "\"{}\" --config \"{}/{}.json\"",
        exe_path.display(),
        config_base.display(),
        "%I"
    );

    let tools_dir = crate::youtube::setup::resolve_paths().ok().map(|p| p.lib_dir);
    let unit = unit_file_contents(&exec_start, &config_base, tools_dir.as_deref());
    std::fs::write(&service_path, unit)?;

    if let Err(e) = Command::new("systemctl")
        .args(["--user", "daemon-reload"])
        .status()
    {
        tracing::warn!("Failed to run systemctl daemon-reload: {e}");
    }

    Ok(config_base)
}

pub fn offer_unit_refresh() {
    let service_path = systemd_dir().join(SERVICE_NAME);
    let Ok(contents) = std::fs::read_to_string(&service_path) else {
        return;
    };
    if unit_version_from_contents(&contents) >= UNIT_FILE_VERSION {
        return;
    }
    println!("\nYour systemd service file was generated by an older version;");
    println!("this release improves it (sandboxing, restart behavior).");
    println!("Rewriting replaces any manual edits you made to it.");
    if prompt_yes_no("Rewrite the service file now?") {
        match write_unit_file() {
            Ok(_) => println!("Service file updated (takes effect on the next bot restart)."),
            Err(e) => println!("Could not update the service file: {e}"),
        }
    } else {
        println!("Keeping the current file. Update later with: ttspotify --install-service");
    }
}

pub(crate) fn unit_file_contents(
    exec_start: &str,
    config_dir: &Path,
    tools_dir: Option<&Path>,
) -> String {
    let tools_rw = tools_dir
        .map(|d| format!("ReadWritePaths=-{}\n", d.display()))
        .unwrap_or_default();
    format!(
        r#"# ttspotify-unit-version: {unit_version}
[Unit]
Description=TTSpotify Bot (%i)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory={config_dir}
ExecStart={exec_start}
Restart=on-failure
RestartPreventExitStatus={config_exit}
RestartSec=2

# Sandbox: everything is read-only to the bot except the paths below.
ProtectSystem=strict
PrivateTmp=true
NoNewPrivileges=true
ReadWritePaths=-{config_dir}
{tools_rw}ReadWritePaths=-%h/.local/share/ttspotify
ReadWritePaths=-%h/.cache

[Install]
WantedBy=default.target
"#,
        unit_version = UNIT_FILE_VERSION,
        config_dir = config_dir.display(),
        config_exit = crate::config::EXIT_CONFIG_ERROR,
    )
}

pub fn uninstall_service() -> Result<(), BotError> {
    let service_path = systemd_dir().join(SERVICE_NAME);
    if service_path.exists() {
        std::fs::remove_file(&service_path)?;
        if let Err(e) = Command::new("systemctl")
            .args(["--user", "daemon-reload"])
            .status()
        {
            tracing::warn!("Failed to run systemctl daemon-reload after removing service: {e}");
        }
        println!("TTSpotify service removed.");
        println!("Running instances are not affected until stopped.");
    } else {
        println!("No service file found at {}", service_path.display());
    }
    Ok(())
}
