pub mod audio;
pub mod bot;
pub mod cli;
pub mod config;
pub mod domain;
pub mod error;
pub mod i18n;
pub mod logging;
pub mod player;
#[cfg(target_os = "linux")]
pub mod daemon;
pub mod services;
pub mod spotify;
pub mod settings;
pub mod track;
pub mod update;
pub mod tt;
pub mod wizard;
pub mod youtube;

